### ISSUE TITLE
toochain.mk

### ISSUE THREAD

**Issue by leeehui** [OP-TEE/build#216]
Hi, I am using the build script for fvp.  when it comes to the step "make toolchains", I found that "curl" can not get the file and just stopped at "Downloading ...".  I changed the "http" to "https", then it worked. 
So, I wonder if we should move to https from the origin?

**Comment by vchong** [comment]
Tried from 2 different networks and seems to be working fine with http.

**Comment by jforissier** [comment]
OTOH, HTTPS is usually recommended since more secure.

**Comment by leeehui** [comment]
maybe this is caused by net environment......anyway, https is more secure and finally worked for me. 
thx.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/build/pull/218
