### ISSUE TITLE
Hikey960 bring up wifi interface

### ISSUE THREAD

**Issue by sagr4019** [OP-TEE/build#262]
Hi,
Iḿ using the Makefile hikey960.mk for building and flashing a Hikey960.
But I don't have a wifi interface. I tried to add to the buildroot conf the following packages 
BR2_PACKAGE_LINUX_FIRMWARE=y
BR2_PACKAGE_LINUX_FIRMWARE_TI_WL18XX=y
and 
BR2_PACKAGE_WPA_SUPPLICANT=y
..
But still no change.

**Comment by SilvaMatteus** [comment]
Hi.
Is there any update on this?

**Comment by jforissier** [comment]
https://github.com/OP-TEE/build/pull/386
