### ISSUE TITLE
building on rpi3 fails

### ISSUE THREAD

**Issue by zatkh** [OP-TEE/build#266]
I updated the build repo for rpi3 and it fails now with this error:
optee_test/host/xtest/regression_1000.c
cc1: error: for_gp/include: No such file or directory [-Werror=missing-include-dirs]
is there any stable version of rpi3.xml manifest?can not init with rpi3_stable  anymore

**Comment by jforissier** [comment]
Hi @zatkh,

It is a known issue (https://github.com/OP-TEE/optee_test/issues/285) that is being worked on (https://github.com/OP-TEE/optee_test/pull/286).

In the mean time, you may revert commit 43d58a5fce8f ("xtest: Makefile: link against OpenSSL if MBed TLS is enabled in TA") in optee_test, or checkout an earlier commit, or build with `CFG_TA_MBEDTLS=n`. Sorry for the inconvenience.
