### ISSUE TITLE
rpi3_stable.xml not available

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/build#271]
rpi3_stable.xml is stated as available, but it's not:

`repo init -u https://github.com/OP-TEE/manifest.git -m rpi3_stable.xml`

`fatal: manifest 'rpi3_stable.xml' not available
fatal: manifest rpi3_stable.xml not found`

**Comment by jbech-linaro** [comment]
I'll take the blame for this one. We removed the stable manifests starting from the 3.1.0 release. It is still possible to get hold of old stable releases, but that require one to checkout a certain commit manually. I have still on my to-do to update our README's with information how to get stable versions as it is now as well as getting older stable releases. I'll mark this as a bug a and assign it to myself.

In the mean time here is the stable branch corresponding to 3.1.0 to use with manifest (repo init ...):
https://github.com/OP-TEE/manifest/tree/3.1.0

**Comment by jbech-linaro** [comment]
I will send a patch for this later today.
