### ISSUE TITLE
Invalid packages

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/build#272]
The readme states the build is done using Ubuntu but references invalid packages. The following should be used instead:

`apt-get install libc6-dev-i386 libstdc++6 libz1`

**Comment by jbech-linaro** [comment]
I took the current apt-get pre-req line earlier today when working with RPi3 instructions. Seemed to work, still an issue on your side?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
