### ISSUE TITLE
Poplar board instructions missing

### ISSUE THREAD

**Issue by gsora** [OP-TEE/build#280]
I see the Poplar board is officially supported, but I can't find any reference to the build instruction (for example, ti.md for Texas Instruments boards or rpi3.md for the Raspberry Pi 3).

Where can I find them? 

Thanks.

**Comment by jdeus** [comment]
They are on the right in this table: https://github.com/OP-TEE/build#user-content-6-manifests

**Comment by gsora** [comment]
They don't seem to be available, there's just a "[]" in the Poplar row.

**Comment by gsora** [comment]
Oh, thanks a lot, I'll check out `flash-help` then!
