### ISSUE TITLE
Stuck in xtest

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/build#281]
When running xtest on a RPi 3 B, it gets stuck at "regression_1004 Test User Crypt TA"

Is it a known issue ?

**Comment by etienne-lms** [comment]
hello @jdeus,
It is likely the tee-supplicant is not running. Try from shell `tee-supplicant &` and run **xtest** again.

**Comment by jdeus** [comment]
@etienne-lms Thanks, looks like it wasn't started automatically
