### ISSUE TITLE
Building examples

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/build#282]
Hi all,

Currently trying to build the optee examples. I followed the build instructions and I'm able to run xtests. How are you supposed to build these examples ?

cd ~/devel/optee/build
make optee-examples-common CROSS_COMPILE=/root/devel/optee/toolchains/aarch64/bin/aarch64-linux-gnu-
make: *** No rule to make target 'optee-client', needed by 'optee-examples-common'.  Stop.

**Comment by jdeus** [comment]
Solution:

Edit ~/devel/optee/build/common.mk:

replace:
optee-examples-common: optee-os optee-client

by:
optee-examples-common: optee-os-common optee-client-common

**Comment by igoropaniuk** [comment]
Hi @jdeus,
Currently `optee-examples` target is built implicitly within `buildroot` target, to rebuild it just run `make buildroot`.

**Comment by igoropaniuk** [comment]
@jdeus https://github.com/OP-TEE/build/blob/master/common.mk#L197
