### ISSUE TITLE
Buildroot error while compiling optee with gstreamer library

### ISSUE THREAD

**Issue by ArunSahu42** [OP-TEE/build#295]
I am trying to build OPTEE with gstreamer library
using the following command
make BR2_PACKAGE_GSTREAMER=y -j2 and getting below error.
Please help me for solving this issue.Thanks in advance

checking for FAMOpen in -lfam... no
configure: WARNING: *** FAM support will not be built (FAM library not found) ***
checking for getxattr in -lc... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for XATTR_NOFOLLOW... no
checking for LIBMOUNT... no
configure: error: *** Could not find libmount
package/pkg-generic.mk:211: recipe for target '/home/sahuuaru/Q8TEE/out-br/build/libglib2-2.56.1/.stamp_configured' failed
make[2]: *** [/home/sahuuaru/Q8TEE/out-br/build/libglib2-2.56.1/.stamp_configured] Error 1
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/sahuuaru/Q8TEE/out-br'
common.mk:198: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

**Comment by jbech-linaro** [comment]
Closing as this is a duplicate to https://github.com/OP-TEE/optee_os/issues/2505.
