### ISSUE TITLE
Arrow keys not working in menu

### ISSUE THREAD

**Issue by r4rounak** [OP-TEE/build#303]
I followed the instructions for Hikey 960. I was getting Synchronous Exception when trying to flash ptable. So for recovery I used binaries from https://snapshots.linaro.org/96boards/reference-platform/components/uefi-staging/76/hikey960/debug/ instead of the ones available under tools-images-hikey960. After reboot I pressed Esc in the console. The menu was displayed but the arrow keys were not working. Return key worked, but nothing else did. What am I doing wrong ?

**Comment by jforissier** [comment]
Try `^` (caret) and `v`. Apparently, Grub is not smart enough to understand the real arrow keypresses :-/

**Comment by r4rounak** [comment]
@jforissier Your solution worked. The arrow keys do work in a similar interface that is shown after the recovery binaries are loaded using hikey_idt and I press RETURN in the console. But they don't work in the menu that is shown after reboot. I wonder why the implementations are different.
I am closing the issue because my problem is solved.
