### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Sun2018421** [OP-TEE/build#304]
I found this error when I first ran it.
The device is a virtual machine ubuntu 16.04 120g hard disk 4g memory.
I feel that it is a memory problem.
![img_3849](https://user-images.githubusercontent.com/38587877/45430283-a78c1700-b6d7-11e8-920f-59b527047079.PNG)
![img_3850](https://user-images.githubusercontent.com/38587877/45430301-af4bbb80-b6d7-11e8-9873-1e3c81ba789a.PNG)
![img_3851](https://user-images.githubusercontent.com/38587877/45430303-b07ce880-b6d7-11e8-820b-174cf931381c.PNG)

**Comment by Sun2018421** [comment]
i am poor ai English

**Comment by jforissier** [comment]
The root fs (`./out-br/images/rootfs.cpio.gz`) failed to build for some reason. Try `make buildroot` and look for errors.

**Comment by Sun2018421** [comment]
Thanks you ,i will try it

**Comment by Sun2018421** [comment]
I want to install OP-TEE on rpi3 , so i download rp3.xml . After making toolchains ,  i make all run it on ubuntu 16.04LTS . 
It tells me 
make[1]:leaving directory '/home/sun/devel/op-tee/out-br'
make:*** NO rule to make target 'run'. stop
why?

**Comment by jforissier** [comment]
Target "run" is for emulated targets only (QEMU, FVP). You probably need to "make flash"

**Comment by Sun2018421** [comment]
it tells me 
make:*** No rule to make target 'flash' . stop
I run it on my ubuntu , but i want to install OP-TEE on my rp3 . should i  run it on rp3 or ubuntu.

**Comment by Sun2018421** [comment]
Thanks you very much , i will read it carefully again . :)
