### ISSUE TITLE
Make xtest fails

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/build#310]
Hi,

Currently experiencing problems when building xtest (platform=rpi3):

cd ~/devel/optee/build
make xtest-common
**make: *** No rule to make target 'optee-client', needed by 'xtest-common'.  Stop.**

**Comment by jbech-linaro** [comment]
@jdeus we have another OP-TEE release (v3.3.0) targeted for the 5th of October, so probably me or someone else is going to try the RPi3 a try any day, so stay tuned.

**Comment by jbech-linaro** [comment]
But hey! `make xtest-common` is not what you are supposed to run. That the old legacy way of building. You should build xtest using buildroot. I.e., simply run `make run` instead.

**Comment by jdeus** [comment]
Turns out I also have the same issue when running a simple make build (not run, as I'm on the rpi3): https://github.com/OP-TEE/build/issues/282

I think it might be the cause of my issue there, as benchmark.ta is missing: https://github.com/OP-TEE/optee_os/issues/2553

**Comment by jbech-linaro** [comment]
RPi3 issues has been sorted out, please see for example: https://github.com/OP-TEE/optee_os/issues/2783 https://github.com/OP-TEE/optee_os/issues/2770. Closing the ticket.
