### ISSUE TITLE
Implementing own system call in optee 

### ISSUE THREAD

**Issue by Anushalagadapati** [OP-TEE/build#312]
I tried to implement my own system call "hello" in optee, for that i wrote the prototype for sys_hello function in qemu/linux/arch/sh/include/asm/syscalls_64.h and function definition in qemu/linux/arch/arm/kernel/module.c and i assigned system call number in qemu/linux/arch/x86/entry/syscalls/syscall_64.tbl.
When i am calling this function from TA it shows implicit declaration of function 'sys_hello' .Can any one help me how to overcome this error.

**Comment by jbech-linaro** [comment]
You also need to add the same in libutee. Search for UTEE/utee and you will see how it is used.

**Comment by jforissier** [comment]
@Anushalagadapati the files you are mentioning are Linux kernel, not OP-TEE...
