### ISSUE TITLE
Can't find optee.bin file

### ISSUE THREAD

**Issue by gperezalbaUGR** [OP-TEE/build#330]
Hi,
I'm following this blog to make a verified boot of OP-TEE on RPi3 (https://blog.crysys.hu/2018/06/verified-boot-on-the-raspberry-pi/)
To create the signed image I need to do:
`ln -s ../optee/arm-trusted-firmware/build/rpi3/debug/optee.bin`
I can't find optee.bin file, there are another 6 binaries and I don't know if one of those is the correct or not...
Maybe another possibility for the binary is the /optee/optee_os/out/arm/core/tee-header_v2.bin ?
Can you please help me?
Thank you

**Comment by gperezalbaUGR** [comment]
Yes, I know this blog is not related with you, but I thought maybe you can help me to find the file.
I know there was a time when optee.bin file existed in the directory optee/arm-trusted-firmware/build/rpi3/debug/ , I've seen another issue where the file is mentioned saying it existed but it is not present anymore https://github.com/OP-TEE/optee_os/issues/1367#issuecomment-282759953
The file is supposed to be the OP-TEE OS core and maybe it has another name now...

> Have you tried putting together a build according to our official instructions in this particular git?

Yes your official instructions works, I just wanted to add a a verification step... 
I'm also trying to contact the author of the blog

**Comment by johnphilby** [comment]
I too can confirm that optee.bin isn't present in rpi3 tag 3.3 but does exist in the 3.2 version using build instructions as mentioned in the official Linaro op-tee. In 3.2 version optee.bin is generated using the commands

```
$ dd if=/dev/zero of=scratch bs=1c count=131072
$ cat bl31.bin scratch > bl31.tmp
$ dd if=bl31.tmp of=bl31.head bs=1c count=131072
$ cat bl31.head tee-pager.bin > optee.bin
```

Whereas in 3.3 they use the Firmware Image Package (FIP) tool to generate a fip.bin that contains bl2.bin and bl31.bin.

`$ fiptool create --tb-fw bl2.bin --soc-fw bl31.bin fip.bin`

> Maybe another possibility for the binary is the /optee/optee_os/out/arm/core/tee-header_v2.bin ?

In my limited understanding, that would be "armstub8.bin". This binary contains bl1 and fip i.e
armstub8.bin = bl1.bin + padding + fip.bin (where fip.bin = bl2.bin + bl31.bin)

So, you might want to try and use "armstub8.bin". Do post your outcome.

**Comment by jbech-linaro** [comment]
@johnphilby related, we are (hours) away from releasing OP-TEE 3.4.0. The RC-tag has been tested OK (https://github.com/OP-TEE/optee_os/pull/2735#issuecomment-455213788).

**Comment by johnphilby** [comment]
@jbech-linaro oh! yes, I have been following that thread and have verified your fixes as per comment https://github.com/OP-TEE/build/issues/325#issuecomment-454968016 But I believe the missing "optee.bin" report here isn't related to that.

Btw, have been watching your videos. Huge fan! And Jens Wiklander (though he doesn't say much). :-)

**Comment by jbech-linaro** [comment]
Ah, I've re-read your comment, yes between 3.2 and 3.3 we changed the boot to a more correct boot, so yes, the `armstub8.bin` is what you are saying, the TF-A binaries + OP-TEE binaries. I.e. `optee.bin` is gone after the change I refer to (https://github.com/OP-TEE/build/commit/2e947f2ee5ae8d2fa3624f90c893f901187dd0b0#diff-a83f16c190650dabd20f7397985adb35L174).

Also, thanks for the nice comment about the videos! :)

**Comment by jbech-linaro** [comment]
I think we have sorted this out ([here](https://github.com/OP-TEE/build/issues/325#issuecomment-454412190)) so I'm closing the ticket.
