### ISSUE TITLE
Running Docker in richOS

### ISSUE THREAD

**Issue by piachristel** [OP-TEE/build#356]
Hi! 

I am using the manifest `qemu_v8.xml`, branch 3.4.0.

a.) Is there an option to run Docker in the richOS?
b.) Or more general: how can I add packages to be used in the richOS?

What I have done:
1. Adding `@echo "BR2_PACKAGE_DOCKER=y" >> ../out-br/extra.conf` to `build/common.mk`
2. `make clean` in `build/` dir
3. `make -j$(nproc)` in `build/` dir
4. `make run`in `build/` dir
But then in normal world console, `docker` gives `-sh: docker: not found`

**Comment by jbech-linaro** [comment]
> a.) Is there an option to run Docker in the richOS?

Good question. It's not really related to OP-TEE at all, it's a pure question whether you can run Docker on a root fs produced by Buildroot. Maybe better to post a question at the [Buildroot mailinglist](https://www.buildroot.org/support.html)?

> b.) Or more general: how can I add packages to be used in the richOS?

What you've done is in accordance to what we normally do when we are trying to enable packages supported by Buildroot, so all that seems good. What you can try before asking for help at the Buildroot mailinglist is to to just `rm -rf <optee-project>/out-br` and them rebuild everything. That might be the trick in case there's stale files, configs etc.
