### ISSUE TITLE
Power-off Data Stability Test

### ISSUE THREAD

**Issue by zhuzhizhan** [OP-TEE/build#369]
Hi, I have maked device power-down randomly and find that some error will occur when shutting down power and optee writing data occur at the same time. So do the optee have necessary to do data stability test?

**Comment by jenswi-linaro** [comment]
We haven't done these kinds of tests before.
The uncertainties are two the file systems, REE FS and RPMB FS.

**Comment by zhuzhizhan** [comment]
I test it with RPMB FS. 
Do you  plan to do this test furture?

**Comment by jenswi-linaro** [comment]
I don't think we have the resources to do so. We're interested in getting in required fixes though.

**Comment by zhuzhizhan** [comment]
Got it. Thanks for your kind reply.
