### ISSUE TITLE
Cannot build trusted app including stdio.h

### ISSUE THREAD

**Issue by sheepNo** [OP-TEE/build#377]
I'm trying to get create my own trusted app example. I need to read/write a file on the disk using `fwrite` (for example). I've included `stdio.h` but ended up with this very interesting error:
```
chall_resp_ta.c:127:3: error: implicit declaration of function ‘fwrite’ [-Werror=implicit-function-declaration]
   fwrite(buffer, 8, 16, fp);
   ^~~~~~
chall_resp_ta.c:127:3: warning: incompatible implicit declaration of built-in function ‘fwrite’
chall_resp_ta.c:127:3: note: include ‘<stdio.h>’ or provide a declaration of ‘fwrite’
chall_resp_ta.c:5:1:
+#include <stdio.h>
 #include <stdio.h>
chall_resp_ta.c:127:3:
   fwrite(buffer, 8, 16, fp);
```

Long story short, I don't want to use the secure storage functions from core as those files will be presented to another computer through UMS. There is no use encrypting them/separating them from normal world.

Is there a solution to this problem or am I forced to write those files from normal world ? Maybe I overlooked something from Core which could do that for me ?

**Comment by jforissier** [comment]
Hi @sheepNo,

> am I forced to write those files from normal world ?

I'm afraid you are... Secure world does not provide an API to deal with files in the normal world. It's usually a good thing to have more code in the least privileged level anyway.
