### ISSUE TITLE
Extend os capabilities

### ISSUE THREAD

**Issue by DimJ** [OP-TEE/build#410]
I have successfully built and deployed my application (optee_examples) in raspberry-pi. However I wan to add a python script that gets data (http) and stores them to the device. How can I extend the software, including Python apps?

**Comment by jforissier** [comment]
The root FS is built using Buildroot. To enable additional packages, you may set additional `BR2_*` variables in `rpm3.mk`. See for instance the [HiKey960 makefile](https://github.com/OP-TEE/build/blob/3a0a0646e574/hikey960.mk#L16-L23).

Custom scripts are added via overlays. For example HiKey960: the files we want to add are [here](https://github.com/OP-TEE/build/tree/3a0a0646e574/br-ext/board/hikey960/overlay), they are added to the root FS thanks to [this declaration](https://github.com/OP-TEE/build/blob/3a0a0646e574/hikey960.mk#L25) in the Makefile.

**Comment by DimJ** [comment]
@jforissier thanks for the reply. I have to study Buildroot for this task. So this issue is closed.
