### ISSUE TITLE
OP-TEE Support for Qemu on Mingw

### ISSUE THREAD

**Issue by antonionehme** [OP-TEE/build#431]
Hi,

I wonder if OP-TEE has support for Qemu running over windows (MinGW).
My aim is to boot my versatile board through Qemu in a trusted environment (TrustZone).

Thanks!

**Comment by jforissier** [comment]
Hi @antonionehme,

I have never tried working with OP-TEE with MinGW. While it might be possible in theory, you can expect to meet **many** issues before reaching a somewhat working state.
So, if your computer is running Windows natively, I would strongly recommend you boot into Linux VM and do everything from there. VMWare Player or Oracle VirtualBox with Ubuntu 20.04 should be super easy to setup and should work flawlessly.

**Comment by antonionehme** [comment]
Many thanks for the quick response!
