### ISSUE TITLE
qemu_v8: there is no hvmloader in xen

### ISSUE THREAD

**Issue by dakexiaoying** [OP-TEE/build#509]
I am a novice and have recently been learning the virtualization part of OP-TEE. 
I got the latest version of OP-TEE, set XEN_BOOT = y and build the whole project successfully. However,  when I tried to create the virtual machine, it failed. 
![error](https://user-images.githubusercontent.com/46088061/127475684-6d865d90-db45-4a4b-8166-b3cf82a53528.png)
There is no ’boot‘ folder in '/usr/lib/xen'.
Do you know what might cause this problem? I can't find the answer on the Internet.

**Comment by ruchi393** [comment]
What we use at our end guest.cfg which you can find in build/qemu_v8/xen folder on host :

Contents of guest.cfg given below - 
kernel="/mnt/host/linux/arch/arm64/boot/Image"
memory=128
vcpus=1
command="console=hvc0 earlycon=xenboot"
ramdisk = "/mnt/host/out-br-domu/images/rootfs.cpio.gz"
name="domu"
tee="optee"

Does this work for you ?

**Comment by dakexiaoying** [comment]
Thank you for your reply!
Yes, it works.
So, is it normal that there is no 'boot' folder in 'usr/lib/xen' ?

**Comment by ruchi393** [comment]
> Thank you for your reply!
> Yes, it works.
> So, is it normal that there is no 'boot' folder in 'usr/lib/xen' ?

Sorry, but I am not sure about this boot folder.
