### ISSUE TITLE
Custom soc_term vs telnet

### ISSUE THREAD

**Issue by b49020** [OP-TEE/build#511]
OP-TEE build currently uses custom [soc_term](https://github.com/linaro-swg/soc_term) application to access two terminals corresponding to secure world and normal world. I think similar behaviour can be achieved using `telnet` as follows:

In Qemu cmdline use:

```
-serial telnet:localhost:54320,server,nowait \
-serial telnet:localhost:54321,server,nowait \
```

And while launching new terminals, we can simply execute:

```
$ telnet localhost 54320
$ telnet localhost 54321
```
Thoughts?

**Comment by jforissier** [comment]
I think it's a good idea. I remember trying `telnet` out of curiosity but I didn't know about the QEMU `telnet:` option so that didn't work...

**Comment by b49020** [comment]
Thanks @jforissier, I will create a PR for this feature.

**Comment by b49020** [comment]
https://github.com/OP-TEE/build/pull/512
