### ISSUE TITLE
FVP model to use

### ISSUE THREAD

**Issue by ruchi393** [OP-TEE/build#515]
I downloaded the following FVP model from here - Armv8-A Foundation AEM FVP
https://developer.arm.com/tools-and-software/simulation-models/fixed-virtual-platforms/arm-ecosystem-models

When trying to use it with fvp.xml manifest, I end up with following logs-

Fast Models [11.15.14 (Jun 23 2021)]
Copyright 2000-2021 ARM Limited.
All Rights Reserved.

terminal_0: Listening for serial connection on port 5000
terminal_1: Listening for serial connection on port 5001
terminal_2: Listening for serial connection on port 5002
terminal_3: Listening for serial connection on port 5003
Visualization web server started on port 2001

Warning: Foundation_AEMvA: Attempted to access VE CS3 space: Read 1 bytes from 0x1c050fe0.
In file: (unknown):0
In process: Foundation_AEMvA.thread_p_6 @ 1638508730 ns

Has anyone tried this out ? Any pointers on what could be going wrong here ?

**Comment by jenswi-linaro** [comment]
I've seen similar warnings. They are from what I've understood more or less harmless in our context.

**Comment by ruchi393** [comment]
Thanks.
