### ISSUE TITLE
Leaving directory: make[1]: Leaving directory '/home/hira/optee-project/u-boot' make: *** [Makefile:106: u-boot] Error 2

### ISSUE THREAD

**Issue by fakhruddinbabor7** [OP-TEE/build#566]
when I'm giving command "make run" , I'm getting the following error:
 
make[1]: Leaving directory '/home/hira/optee-project/u-boot'
make: *** [Makefile:106: u-boot] Error 2

**Comment by etienne-lms** [comment]
Did you clone this build.git repository only?
You should fetch OP-TEE/manifest and build from it. See for example [build instructions for platform qemu_v8.mk](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#id3).
