### ISSUE TITLE
nanopb_pb2 build error

### ISSUE THREAD

**Issue by luca-fancellu** [OP-TEE/build#595]
Hi,

I'm getting an error when try to build the overall optee system, this is the error:

`
Traceback (most recent call last):
  File "/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-src/generator/nanopb_generator.py", line 50, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-src/generator/protoc", line 6, in <module>
    from nanopb_generator import invoke_protoc
  File "/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-src/generator/nanopb_generator.py", line 71, in <module>
    import proto.nanopb_pb2 as nanopb_pb2
  File "/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-src/generator/proto/__init__.py", line 33, in <module>
    invoke_protoc(argv=cmd)
  File "/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-src/generator/proto/_utils.py", line 43, in invoke_protoc
    return subprocess.call(argv)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'
make[3]: *** [CMakeFiles/generate_nanopb_pb2.py.dir/build.make:80: nanopb_pb2.py] Error 1
make[3]: Leaving directory '/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-build'
make[2]: *** [CMakeFiles/Makefile2:124: CMakeFiles/generate_nanopb_pb2.py.dir/all] Error 2
make[2]: Leaving directory '/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-build'
make[1]: *** [Makefile:149: all] Error 2
make[1]: Leaving directory '/home/lucfan01/optee_project/out/ts-build/crypto/_deps/nanopb-build'
CMake Error at /home/lucfan01/optee_project/trusted-services/tools/cmake/common/LazyFetch.cmake:209 (message):
  Installing failed.  2
Call Stack (most recent call first):
  /home/lucfan01/optee_project/trusted-services/external/nanopb/nanopb.cmake:67 (LazyFetch_MakeAvailable)
  /home/lucfan01/optee_project/trusted-services/deployments/crypto/crypto.cmake:64 (include)
  CMakeLists.txt:38 (include)
`

These are my steps:

1. mkdir optee_project && cd optee_project
2. repo init -u https://github.com/OP-TEE/manifest.git -m fvp-ts.xml -b master
3. repo sync -j4 --no-clone-bundle
4. ln -s ../Base_RevC_AEMvA_pkg Base_RevC_AEMvA_pkg
5. cd build
6. make -j2 toolchains
7. make run

**Comment by jbech-linaro** [comment]
@balint-dobszay-arm , this is the setup that you're maintaining (`fvp-ts.xml`), please have a look if you find some time for it.

**Comment by gyuri-szing** [comment]
Hi @luca-fancellu,

Unfortunately, the OP-TEE documentation is not polished enough related to the "SPMC" feature and the Trusted Services dependency. We will fix that in the near future, hopefully till v3.20 gets released.

Please read TS set-up instructions here: https://trusted-services.readthedocs.io/en/integration/developer/software-requirements.html. The please run `pip install -r <ts-root-directory>/requirements.txt`. Optionally you might want to create a "virtual environment" for TS and activate it first: `pyton3 -m venv ~/ts-venv && ~source /ts-venv/bin/activate` 

If this is not helping, then please share details about your build environment. Which version of which OS are you running?

/George
