### ISSUE TITLE
How the memory size set in the qemu.mk file (such as 1057 at this time) is allocated to REE and TEE?

### ISSUE THREAD

**Issue by wsp1999** [OP-TEE/build#630]
.PHONY: run-only
run-only:
	$(call check-terminal)
	$(call run-help)
	$(call launch-terminal,54320,"Normal World")
	$(call launch-terminal,54321,"Secure World")
	$(call wait-for-ports,54320,54321)
	(cd $(QEMU_PATH)/arm-softmmu/qemu-system-arm \
		-nographic \
		-serial tcp:localhost:54320 -serial tcp:localhost:54321 \
		-s -S -machine virt -machine secure=on -cpu cortex-a15 \
		-d unimp  -semihosting-config enable,target=native \
		-m 1057 \
		-bios $(ROOT)/out/bios-qemu/bios.bin \
		$(QEMU_EXTRA_ARGS) )

How the memory size set in the qemu.mk file (such as 1057 at this time) is allocated to REE and TEE?

**Comment by jenswi-linaro** [comment]
OP-TEE and the Linux kernel reads this memory configuration from the DTB which QEMU generates when initializing. The value 1057 is mostly used for legacy reasons, it might be possible to use a more even value these days.

**Comment by wsp1999** [comment]
Then, How do I change the memory ratio between TEE and REE?

**Comment by jenswi-linaro** [comment]
The secure memory is using a fixed number hardcoded into QEMU, this is only non-secure memory. Unless you're using a static carveout for share memory everything is used by the REE.

**Comment by wsp1999** [comment]
Does this means that 1057 is only non-secure memory? Where should I modify the fixed number to set the size of the safe memory?

**Comment by jenswi-linaro** [comment]
It's hardcoded in `hw/arm/virt.c` in the QEMU source, search for VIRT_SECURE_MEM. If stuff breaks I'm not able to help.

**Comment by wsp1999** [comment]
I tried to modify this value, the compilation passed normally, but there are always errors during the run. What is the reason for this?

**Comment by wsp1999** [comment]
If I want to modify the size ratio of safe and non-safe memory in a project, what should I do？

**Comment by n43e125** [comment]
I monitored that when setting memory larger than 1057 while having multiple core settings with -smp 4, it sometimes failed to bring up core 2,3,4. Are there any constraints on memory setting?
