### ISSUE TITLE
[RFC] Makefiles for RISC-V platforms

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/build#649]
Dear maintainers,

To let more RISC-V people build and try OP-TEE, it is helpful to have some Makefiles for RISC-V platforms.
Are there any recommendations for starting this work?

For example, add the following conditions into `common.mk` and `toolchain.mk`:
```
ifeq ($(ARCH), ARM)
...
else ifeq ($(ARCH), RISC-V)
...
endif
```

Or we should have another dedicated repository, such as `OP-TEE/build_riscv` ?

**Comment by jenswi-linaro** [comment]
I believe keeping it all in the present build repository is preferable.

**Comment by gagachang** [comment]
OK Thanks, I will prepare for it!

**Comment by jenswi-linaro** [comment]
Yes, I guess we can do that. Please keep that in a separate commit.

**Comment by gagachang** [comment]
> Yes, I guess we can do that. Please keep that in a separate commit.

Please check https://github.com/OP-TEE/build/pull/650.

**Comment by gagachang** [comment]
Work in progress.

**Comment by gagachang** [comment]
Please refer to https://github.com/OP-TEE/build/pull/666

**Comment by gagachang** [comment]
Works on `common.mk`: https://github.com/OP-TEE/build/pull/669

**Comment by gagachang** [comment]
Still WIP
