### ISSUE TITLE
Optee build failed on RPi 3B+ due to make[4]: *** [Makefile:2377: s-automata] Error 137

### ISSUE THREAD

**Issue by fakhruddinbabor7** [OP-TEE/build#656]
When I run the command 'make toolchains", I got the following error:
/bin/bash: line 1: 22175 Killed                  build/genautomata ../../gcc/common.md ../../gcc/config/aarch64/aarch64.md insn-conditions.md > tmp-automata.c
make[4]: *** [Makefile:2377: s-automata] Error 137
make[4]: *** Waiting for unfinished jobs....
/bin/bash ../../gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/bash ../../gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/bash ../../gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
rm gcc.pod
make[3]: *** [Makefile:4389: all-gcc] Error 2
make[2]: *** [package/pkg-generic.mk:293: /home/pi/rpi3/out-aarch64-sdk/build/host-gcc-initial-10.4.0/.stamp_built] Error 2
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/pi/rpi3/out-aarch64-sdk'
make: *** [toolchain.mk:107: /home/pi/rpi3/build/../toolchains/aarch64/.done] Error 2

**Comment by Uestcnew** [comment]
i also have the error 137 in rpi3B+,did you get solution?
