### ISSUE TITLE
AMD Versal ACAP - do not update to BSP 2023.1

### ISSUE THREAD

**Issue by ldts** [OP-TEE/build#684]
There has been an ABI change on the latest BSP and because of this, OP-TEE will fail to communicate with the PLM in the MicroBlaze.

**Comment by jforissier** [comment]
That's unfortunate. Any way OP-TEE could detect the new ABI at runtime?

**Comment by ldts** [comment]
We are looking into this and discussing with AMD but nothing as yet.

**Comment by ldts** [comment]
BSP 2023.02 will allow us to interrogate the ABI version for each PLM service and develop the corresponding set of fixes. Once it is out we'll start working on it.
