### ISSUE TITLE
Cannot excute "make toolchains"

### ISSUE THREAD

**Issue by marduino** [OP-TEE/build#70]
Dear sir,

According with "https://github.com/OP-TEE/optee_os/blob/master/README.md#523-get-the-toolchains", command "make toolchains" needs to be excuted to get the toolchains, but to there is not a makefile under "build", 

how to "make toolchains"?

**Comment by vchong** [comment]
Replied on https://github.com/OP-TEE/optee_os/issues/914

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
