### ISSUE TITLE
Differences Between Using Buildroot and OP-TEE Build for OP-TEE Components

### ISSUE THREAD

**Issue by kewer127** [OP-TEE/build#759]
Hi developers,

I found that Buildroot supports the following OP-TEE components:

```
boot/optee-os/
boot/optee-os/optee-os.hash
boot/optee-os/optee-os.mk
package/optee-client/
package/optee-client/optee-client.hash
package/optee-client/optee-client.mk
package/optee-examples/
package/optee-examples/optee-examples.hash
package/optee-examples/optee-examples.mk
package/optee-test/
package/optee-test/optee-test.hash
package/optee-test/optee-test.mk
```

I am wondering what the difference is when using buildroot itself rather than this repository.

**Comment by jbech-linaro** [comment]
It's the same as we have here, it was @etienne-lms who did upstream support in Buildroot to be able to build the ones you listed directly from Buildroot. The official setup you find in the OP-TEE documentation is slighly different, since we clone and work with the OP-TEE gits as standalone gits.

**Comment by kewer127** [comment]
@jbech-linaro  Thanks for clarifying!
