### ISSUE TITLE
How to test and modify fTPM (enabled with buildroot package)

### ISSUE THREAD

**Issue by graziadonghia** [OP-TEE/build#774]
I am trying to implement a fTPM through tpm2-tools and tpm2-tss within OP-TEE. Firstly, I saw [this implementation](https://github.com/jbech-linaro/manifest/tree/ftpm?tab=readme-ov-file), but I could not build it because it was probably tested with an older version of OP-TEE. 
However, #480 has added support for fTPM through buildroot packages, so it should be included in the latest version of OP-TEE. Having said that, how can I execute measured boot and tpm functionalities, after building OP-TEE with buildroot?

**Comment by jenswi-linaro** [comment]
#480 does if I understand it correctly only cover the rootfs part of fTPM. You still need to compile an fTPM TA for OP-TEE.

**Comment by graziadonghia** [comment]
Is there a current implementation of an fTPM TA for the latest version of OP-TEE?
